// Authors: bpross@ucsc.edu, esteggal@ucsc.edu
// TA: Richard Halpert
// Professor: Wesley Mackey
// CMPS 104a

//
// This program, when linked with a parser generated by bison,
// will print out all of the terminal symbols, both as integers
// and as symbols.
//
// Compile with:
//    cc printtokens.c parser.c -o printtokens
//


#include <stdio.h>
#include <string.h>

const char *get_yytname (int);

int main (void) {
   int token;
   for (token = 0; token <= (1<<10); ++token) {
      const char *name = get_yytname (token);
      if (strcmp (name, "$undefined") == 0) continue;
      (void) printf ("%5d %s\n", token, name);
   };
   return 0;
}

void yyerror (void){}

void yylex (void){}

